// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

func init() {
	swag.Register(swag.Name, &s{})
}

type s struct{}

func (s *s) ReadDoc() string {
	return `{"swagger":"2.0","info":{"description":"REST API for tracking personal expenses and incomes.","title":"Expense Tracker API","version":"1.0"},"basePath":"/","paths":{}}`
}
